version: "2"
checks:
  method-lines:
    config:
      threshold: 100
  similar-code:
    enabled: true
    config:
      threshold: 80
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- "config/"
- "deploy/"
- "public/"
- "scripts/"
- "src/tests"
- ".github"
- "**/node_modules/"